### PR TITLE
New shoes

### PR DESCRIPTION
**Pull request by Lewiscowles1986**
## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code has proper inline documentation.

### CODE REVIEW

**Comment by pablinos** [comment]
Hey,

It looks like the problem is with this change:

https://github.com/Lewiscowles1986/gutenberg/blob/ebee8e26c086abe247b18e6d5de7f3dba62856d0/blocks/library/shortcode/block.js#L25-L32

Previously the preview component was only being rendered when the preview prop was true, but now I'm assuming that `isSelected` is false and so it's trying to render the preview. The preview is a connected component and so it's failing because it can't find a store.

I'm not sure if the preview should be rendered by default (I'd have to take a better look at the code) but it would probably be best to test the preview component separately by exporting an unconnected version, something like how [PostPublishButton is tested](https://github.com/WordPress/gutenberg/tree/9c6143b47b980f79c34a2230874bc5636c1a71ef/editor/components/post-publish-button)

I'll have a better look at the code later and see if I can be of more help!

**Comment by Lewiscowles1986** [comment]
> The preview is a connected component and so it's failing because it can't find a store.

That's the bit I'm not understanding as it renders & works. I tried to read up on it, as I assume there is a valid edge-case. Not caring about or wanting to learn react or redux & their nuance is a surprising and formidable barrier to progress resolving.

I'll try to intuit what I can from PostPublishButton :+1:

**Comment by pablinos** [comment]
Yes all that redux stuff can be a headache to begin with. I doubt you'd find it that difficult though. Overall it's probably a worthwhile time investment!

The redux store provides all the data for the components and comes from a top level `Provider` component. This is all setup and available when running the whole of the application, but not during testing. The data in the store is connected to props on the component, so in order to test the component you need to use the unconnected version and manually supply the props (there are other ways, but that's the one generally used).

I think it might be worth taking a look at why it's trying to render the preview by default. Is that expected behaviour? If so, then I think you would want to mock the preview component and test it separately. Add something along the lines of:

```js
jest.mock( '../preview', () => () => '*** Mock(Shortcode Preview) ***' );
```

to the test, and add a test for the preview.

Thanks for working on this!

**Comment by Lewiscowles1986** [comment]
> I think it might be worth taking a look at why it's trying to render the preview by default. Is that expected behaviour? 

Yes it's intentional for preview to be the default. The whole point is that it enables users without a technical background to interact in design / layout without needing development skills. 

If the block defaults to shortcode technical view, it's broken and poorly designed IMO. If the opposite is true, technical users can select the block in-place (also jank AF right now) to edit technical content (shortcode). There should be tests added so that clicking the preview automatically selects the block & blocks interactivity (dumb window vs interactive rendered element).

> If so, then I think you would want to mock the preview component and test it separately. Add something along the lines of:
> jest.mock( '../preview', () => () => '*** Mock(Shortcode Preview) ***' );

@pablinos I'll be honest, if preview is hidden, or artificially tested just because it's poorly written (it's explicitly hard-coded into the shortcode & works when not in isolation, in-browser), then it's a failure of the testing framework, not the code.

I've not found a browser where it has failed to render a shortcode or has emitted new JS errors (sandbox existing component seems to generate some non-breaking errors)

  * Youtube XSS header policy errors (external cantfix)
  * Failed to read the 'cssRules' property from 'CSSStyleSheet': Cannot access rules (a current interest, but from what I've read a chrome/webkit bug [see](https://github.com/odoo/odoo/issues/22517))

**Comment by Lewiscowles1986** [comment]
I believe it's fixed now... Latest build only has timeout on the 3rd test stage.

going to test this build now
[gutenberg.zip](https://github.com/Lewiscowles1986/gutenberg/files/1762497/gutenberg.zip)

**Comment by Lewiscowles1986** [comment]
:laughing: :rofl: tests pass... poxy thing doesn't work now lol

**Comment by Lewiscowles1986** [comment]
Was never intended to be merged...

**Comment by Lewiscowles1986** [comment]
Final build in this branch [gutenberg.zip](https://github.com/Lewiscowles1986/gutenberg/files/1764249/gutenberg.zip)

**Comment by pablinos** [comment]
> Yes it's intentional for preview to be the default. The whole point is that it enables users without a technical background to interact in design / layout without needing development skills.

Ok, that makes sense and is a good way of making the interface more accessible to non-technical users. I'd just make sure that it displays something sensible in the preview before the shortcode is added. Maybe some placeholder information or an example shortcode?

That's just got me thinking about a Scratch style interface for building shortcodes. I'll add that to my 'someday' list of ideas.

> @pablinos I'll be honest, if preview is hidden, or artificially tested just because it's poorly written (it's explicitly hard-coded into the shortcode & works when not in isolation, in-browser), then it's a failure of the testing framework, not the code.

I see what you're saying as it seems like a silly test when you stub out the preview component, but the idea is to make sure that you're testing each component (or unit) in isolation. If there is a problem with the preview component then it shouldn't break the shortcode component too. By mocking the preview component you can check the behaviour of the shortcode component (e.g. that it renders a preview component by default) and then write tests for the preview component's functionality separately. 

> Final build in this branch gutenberg.zip

Is that in a branch somewhere? It would be good to get it as a PR, so the changes can be reviewed.

Glad you got it working and the tests passing!

**Comment by Lewiscowles1986** [comment]
> I'd just make sure that it displays something sensible in the preview before the shortcode is added. Maybe some placeholder information or an example shortcode?

Blank slates. I'll put that on my todo for tomorrow :laughing: 

> That's just got me thinking about a Scratch style interface for building shortcodes. I'll add that to my 'someday' list of ideas.

Another :1st_place_medal: idea

> I see what you're saying as it seems like a silly test when you stub out the preview component, but the idea is to make sure that you're testing each component (or unit) in isolation. If there is a problem with the preview component then it shouldn't break the shortcode component too. By mocking the preview component you can check the behaviour of the shortcode component (e.g. that it renders a preview component by default) and then write tests for the preview component's functionality separately.

Since reading your linked [hackernoon article](https://hackernoon.com/unit-testing-redux-connected-components-692fa3c4441c) I think I understand redux better, but that even blindly I made the right choice, because react is not rendering the shortcodes but acting mostly as an echo for http, I think this made it simpler.

> Is that in a branch somewhere? It would be good to get it as a PR, so the changes can be reviewed.

The branch is https://github.com/Lewiscowles1986/gutenberg/tree/new-shoes. There is a PR to Gutenberg I've cancelled https://github.com/WordPress/gutenberg/pull/5287. I've also posted on the original patch authors PR (they have done a lot of work ~28 days before I came along) https://github.com/WordPress/gutenberg/pull/4710 and linked them to direct line-by-line changes.

It won't be lost I hope, and perhaps all my bemoaning now combined with action can help set a direction or get something passed.

Thanks for your patience, input and expertise

**Comment by pablinos** [comment]
Sorry for the silence, I've been travelling through the snow!

I think this is the key line:

https://github.com/Lewiscowles1986/gutenberg/blob/0fc2c6a17905362c3af15761707d0aac732f14da/blocks/library/shortcode/preview.js#L27

I can't see this global post object being used much and not in this way. It means the component is coupled to a property of the window object, which might cause problems with things like server rendering. Previously the post ID was coming from the Redux store and passed in as a prop. I think that would probably be the preferred way of doing it.

I'll have a read through the original PR and perhaps we can get some of this work added to it. Could you create a branch from the original PR and then get your changes reviewed and merged?

**Comment by Lewiscowles1986** [comment]
Hope you're snow travels went well, I've loved it, but Mamut hiking & climbing boots mean I'm attached to the floor :snowman_with_snow:. 

> I think this is the key line:

Yeah that absolutely sucked, I even considered hiding it in a function that could be overriden

```
postId: (value || function() { return (window._wpGutenbergPost || {}).id; }())
```

I didn't because linting & madness [also this](http://www.codereadability.com/javascript-default-parameters-with-or-operator/). So this became the only way to decouple from redux easily (I tried several alternative methods including ripping out of the window.location.search).

I'll give the PR rebase a go (the source PR repo is a bit of a mess although this was based on that). I was thinking of rebasing from master instead and pulling in changes from the PR as-needed.

**Pull request closed without merging**
